project_structure:
    build: brownie/build
    contracts: brownie/contracts
    interfaces: brownie/interfaces
    reports: brownie/reports
    scripts: brownie/scripts
    tests: brownie/tests

networks:
    default: development
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false

compiler:
    evm_version: null
    solc:
        version: 0.8.18
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3"
            - "solidity-rlp=hamdiallam/Solidity-RLP@2.0.7"
    vyper:
        version: null

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.7.3
    - hamdiallam/Solidity-RLP@2.0.7
