live:
- name: substrate-subnet-network-A
  networks:
  - chainid: 43
    host: http://127.0.0.1:9933/
    id: substrate-subnet-network-A
    name: 'substrate_subnet_network_A'

- name: substrate-subnet-network-B
  networks:
  - chainid: 44
    host: http://127.0.0.1:9944/
    id: substrate-subnet-network-B
    name: 'substrate_subnet_network_B'
