development:
- cmd: ganache-cli
  cmd_settings:
    chain_id: 1338
    accounts: 10
    evm_version: istanbul
    gas_limit: 12000000
    mnemonic: brownie
    port: 7545
  host: http://127.0.0.1
  id: development-two
  name: Ganache-CLI
