name: Docker_build_push

on:
  push:
    branches: main
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    uses: ./.github/workflows/docker_utils.yml
  e2e:
    needs: docker
    runs-on: ubuntu-latest-16-core
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: topos-network
          repo: e2e-tests
          github_token: ${{ secrets.ROBOT_PAT_TRIGGER_E2E_WORKFLOWS }}
          workflow_file_name: frontend:erc20-messaging.yml
          ref: main
          wait_interval: 60
          client_payload: '{ "topos-smart-contracts-docker-tag": "${{ needs.docker.outputs.tags }}" }'
