name: Sequencer-Contracts e2e test

on:
  pull_request:
    branches: main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sequencer-contracts-e2e:
    runs-on: ubuntu-latest-16-core
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: topos-network
          repo: e2e-tests
          github_token: ${{ secrets.ROBOT_PAT_TRIGGER_E2E_WORKFLOWS }}
          workflow_file_name: topos:sequencer-contracts.yml
          ref: main
          wait_interval: 60
          client_payload: '{ "topos-smart-contracts-ref": "${{ github.head_ref }}" }'
